language: c

sudo: required

services:
    - docker

before_install:
    - docker pull amigadev/crosstools:ppc-morphos

addons:
    apt:
        update: true

script:
    - wget -nc http://aminet.net/dev/mui/MCC_TheBar-26.19.lha
    - wget -nc http://www2m.biglobe.ne.jp/~dolphin/lha/prog/lha-114i.tar.gz
    - tar xvfz lha-114i.tar.gz
    - make -C lha-114i
    - cp lha-114i/src/lha dist
    - dist/lha ef MCC_TheBar-26.19.lha
    - docker run --rm -v ${PWD}:/work -it amigadev/crosstools:ppc-morphos bash -c 'cp -r MCC_TheBar/Developer/C/include/* /opt/ppc-morphos/os-include/ && make dist CC=ppc-morphos-gcc LHA=/work/dist/lha ARC=ppc PRO=echo UNM=MorphOS'
    - mkdir artefacts
    - cp dist/tmp/* artefacts
    - sudo make clean CC=ppc-morphos-gcc LHA=dist/lha ARC=ppc PRO=echo UNM=MorphOS

#    - docker run --rm -v ${PWD}:/work -it amigadev/crosstools:ppc-morphos bash -c 'wget -nc http://aminet.net/dev/mui/MCC_TheBar-26.19.lha && wget -nc http://www2m.biglobe.ne.jp/~dolphin/lha/prog/lha-114i.tar.gz && tar xvfz lha-114i.tar.gz && make -C lha-114i && cp lha-114i/src/lha dist && dist/lha ef MCC_TheBar-26.19.lha && cp -r MCC_TheBar/Developer/C/include/* /opt/ppc-morphos/os-include/ && ls -l /opt/ppc-morphos/os-include/mui && make dist CC=ppc-morphos-gcc LHA=/work/dist/lha ARC=ppc PRO=echo UNM=MorphOS && cp dist/tmp/* artefacts && make clean CC=ppc-morphos-gcc LHA=/work/dist/lha ARC=ppc PRO=echo UNM=MorphOS'
#wget https://muidev.de/download/MUI%205.0%20-%20Release/MUI-5.0-2019R2-os4.lha
#lha e -f MUI-5.0-2019R2-os4.lha
#ls SDK/MUI/C/include/
#/opt/ppc-amigaos/ppc-amigaos/SDK/include/include_h/

deploy:
    provider: releases
    api_key: '$GITHUB_API_KEY'
    file_glob: true
    file: "artefacts/*"
    skip_cleanup: true
    draft: true

