language: c

sudo: required

services:
    - docker

before_install:
    - sudo apt-get install lhasa
    - docker pull amigadev/crosstools:ppc-morphos

addons:
    apt:
        update: true

script:
    - wget http://aminet.net/dev/mui/MCC_TheBar-26.19.lha
    - lha e MCC_TheBar-26.19.lha
    - docker run --rm -v ${PWD}:/work -v ${PWD}/MCC_TheBar/Developer/C/include:/tools/usr/include -it amigadev/crosstools:ppc-morphos make -C src -f Make_ami.mak CC=ppc-morphos-gcc OS=MorphOS UNM=MorphOS
