language: c

sudo: required

services:
    - docker

before_install:
    - docker pull amigadev/crosstools:ppc-morphos

script:
    - docker run --rm -v ${PWD}:/work -it amigadev/crosstools:ppc-morphos ppc-morphos-gcc --version
