language: c

sudo: required

services:
    - docker

before_install:
    - docker pull amigadev/crosstools:ppc-morphos

addons:
    apt:
        update: true

script:
    - wget http://aminet.net/dev/mui/MCC_TheBar-26.19.lha
    - wget http://www2m.biglobe.ne.jp/~dolphin/lha/prog/lha-114i.tar.gz
    - tar xvfz lha-114i.tar.gz
    - make -C lha-114i
    - cp lha-114i/src/lha dist
    - ${PWD}/dist/lha e MCC_TheBar-26.19.lha
    - ls -l ${PWD}/dist
    - docker run --rm -v ${PWD}:/work -v ${PWD}/MCC_TheBar/Developer/C/include:/tools/usr/include -it amigadev/crosstools:ppc-morphos make dist CC=ppc-morphos-gcc LHA=/work/dist/lha PRO=echo UNM=MorphOS
